### ISSUE TITLE
can't get the downloadable video+audio link

### ISSUE THREAD

**Issue by KetchupZone** [yausername/youtubedl-android#109]
I want to get the download link of a video from reddit with YoutubeDL and than download it with DownloadManager but I cant get the video+audio downloadable link. I've tried with -f -best but got an error. So far  I've only managed to get the single audio or video link
<code>
YoutubeDLRequest requestDL = new YoutubeDLRequest("https://www.reddit.com/r/arduino/comments/nhruxi/made_a_working_bridge_with_arduino/?utm_medium=android_app&utm_source=share");

                            requestDL.addOption("-f", "best");
            //                requestDL.addOption("-f", "mp4");
            //                requestDL.addOption("-merge-output-format");
            //                request.addOption("-g");
                            VideoInfo response = null;
                            try {
                                response = YoutubeDL.getInstance().getInfo(requestDL);
                            } catch (YoutubeDLException | InterruptedException e) {
                                e.printStackTrace();
                            }
                            System.out.println(response.getUrl());

</code>
but when I do that i get <br>
W/System.err: com.yausername.youtubedl_android.YoutubeDLException: ERROR: requested format not available<br>
my YoutubeDL library is up to date

**Comment by xibr** [comment]
In the link you mentioned, there is no video with audio available, 
![Screenshot from 2021-05-22 22-02-07](https://user-images.githubusercontent.com/20098154/119236608-64052e80-bb49-11eb-8ee5-5407b6d948f4.png)
if you use this command `-g` You will get a link for a video and another link for audio.
If you want to download the video with the audio, use the command `-f best` Because this requires ffmpeg to merge audio with video.

**Comment by KetchupZone** [comment]
Tried with this one that 100% has audio but : https://www.reddit.com/r/2balkan4you/comments/nikyk9/greek_soldier_commiting_a_war_crime_against_a/?utm_medium=android_app&utm_source=share but still got the same error even though I had ffmpeg initialized

**Comment by xibr** [comment]
```
youtube-dl -F "https://www.reddit.com/r/2balkan4you/comments/nikyk9/greek_soldier_commiting_a_war_crime_against_a/?utm_medium=android_app&utm_source=share"
[RedditR] nikyk9: Downloading JSON metadata
[Reddit] oqm7a325wo071: Downloading m3u8 information
[Reddit] oqm7a325wo071: Downloading MPD manifest
[info] Available formats for oqm7a325wo071:
format code          extension  resolution note
hls-0-audio_0        mp4        audio only 
hls-1-audio_1        mp4        audio only 
dash-audio_0_132245  m4a        audio only DASH audio  132k , m4a_dash container, mp4a.40.2 (48000Hz)
hls-340              mp4        288x288     340k , avc1.42001e, video only
hls-437              mp4        288x288     437k , avc1.42001e, video only
hls-532              mp4        320x320     532k , avc1.42001e, video only
dash-video_583104    mp4        240x240    DASH video  583k , mp4_dash container, avc1.4D401E, 30fps, video only
hls-629              mp4        320x320     629k , avc1.42001e, video only
dash-video_774585    mp4        360x360    DASH video  774k , mp4_dash container, avc1.4D401E, 30fps, video only
hls-927              mp4        432x432     927k , avc1.4d001e, video only
hls-1024             mp4        432x432    1024k , avc1.4d001e, video only
dash-video_1149067   mp4        480x480    DASH video 1149k , mp4_dash container, avc1.4D401F, 30fps, video only (best)

```
**(best) is video only** You cannot download a video that contains audio with DownloadManager because reddit it may not provide a video that contains audio. It provides video only and audio only, and you can download video and audio and merge them together by using youtube-dl built-in downloader check out this example [https://github.com/yausername/youtubedl-android/blob/master/app/src/main/java/com/yausername/youtubedl_android_example/DownloadingExampleActivity.java](https://github.com/yausername/youtubedl-android/blob/master/app/src/main/java/com/yausername/youtubedl_android_example/DownloadingExampleActivity.java)

**Comment by KetchupZone** [comment]
than that means that there is no way to avoid dealing with the shit show that Android Storage is.. 
Thanks for the info
