### ISSUE TITLE
Migrate to Kotlin

### ISSUE THREAD

**Issue by JunkFood02** [yausername/youtubedl-android#205]
I think the benefits of using Kotlin need no elaboration 😁

Also, after [replacing](https://github.com/JunkFood02/Seal/commit/48b081bbf1ce57db913d8047cbe75c449d163a14) the Jackson Databind with [kotlinx-serialization](https://github.com/Kotlin/kotlinx.serialization), I noticed a significant improvement in the speed of parsing video information.

**Comment by BobbyESP** [comment]
I made a library following this library's source code in kotlin (but with Jackson). That could help with the rewritten. I'm thinking of moving to DSL, but first I have to make the library work because I don't have the binary python-dependent file of the library.

https://github.com/bobbyesp/spotdl-android

**Comment by JunkFood02** [comment]
I've nearly done this in my fork and going to ship it with Seal's pre-release for testing

**Comment by BobbyESP** [comment]
Nice!

**Comment by JunkFood02** [comment]
I've pushed the [commits](https://github.com/yausername/youtubedl-android/commit/4bbf59ec5c02091cbaf83072435e68840a4e6b76) to the master branch by accident 😂 

Being tested with Seal v1.7.0+, it seems to be working fine
