### ISSUE TITLE
Build youtube-dl

### ISSUE THREAD

**Issue by cassiodanilo** [yausername/youtubedl-android#31]
Is possible for me to build my own version of youtube-dl in your library? And How?

**Comment by yausername** [comment]
Yes, you can replace [library/src/main/res/raw/youtube_dl.zip](https://github.com/yausername/youtubedl-android/blob/master/library/src/main/res/raw/youtube_dl.zip) file with your own version of youtube-dl. Also, you will need to change the `YoutubeDLUpdater.java` class because it currently checks for updates from my [repo](https://github.com/yausername/youtubedl-lazy).
