### ISSUE TITLE
Request AtomicParsley for embed-thumbnail

### ISSUE THREAD

**Issue by xibr** [yausername/youtubedl-android#53]
Hi, Can **AtomicParsley** be added when you have free time?

It is important when adding **--embed-thumbnail**

I did try but I did not succeed.

thanks.

**Comment by bunaif** [comment]
AtomicParsley has been successfully added and working fine.

I changed this line
           ` if not check_executable('AtomicParsley', ['-v']):`
With this line 
            `if not check_executable('libatomicparsley.bin.so', ['-v']):`

in YouTube-dl Library in this file [embedthumbnail.py#L59](https://github.com/ytdl-org/youtube-dl/blob/d5147b65ac3d81b5acb4aa2c4aca008ffd3e7c06/youtube_dl/postprocessor/embedthumbnail.py#L59)

and this line 
            `cmd = [encodeFilename('AtomicParsley', True),`
With this line
            `cmd = [encodeFilename('libatomicparsley.bin..so', True),`
in same file [embedthumbnail.py#L62](https://github.com/ytdl-org/youtube-dl/blob/d5147b65ac3d81b5acb4aa2c4aca008ffd3e7c06/youtube_dl/postprocessor/embedthumbnail.py#L62)

This method was used to build AtomicParsley [BUILD_FFMPEG.md](https://github.com/yausername/youtubedl-android/blob/master/BUILD_FFMPEG.md)

only change `./build-package.sh ffmpeg` to `./build-package.sh atomicparsley`

But the problem is I cannot update the youtube-dl library automatically, the file must be modified [embedthumbnail.py](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/postprocessor/embedthumbnail.py) manually.

i think can this problem fixed here in [youtubedl-lazy](https://github.com/yausername/youtubedl-lazy/).

**Comment by yausername** [comment]
ok. I will update youtubedl-lazy when I get time. Hopefully by tomorrow.

**Comment by bunaif** [comment]
Okay. thank you very much.

**Comment by yausername** [comment]
Hi @xibr ,
I have updated youtubedl-lazy with the embedthumbnail.py patch.

**Comment by xibr** [comment]
Great job, thank you very much. 
I will check it later.
Also I will add files if someone wants to use the AtomicParsley library.

thanks.

**Comment by yausername** [comment]
@xibr prebuilt binaries for packages can also be taken from https://termux.net/dists/stable

**Comment by xibr** [comment]
> @xibr prebuilt binaries for packages can also be taken from https://termux.net/dists/stable

Good, I will check it.

also I have this error 

```
post_process files_to_delete, info = pp.run(info) File "/data/data/ibr.dev.proapps.debug/no_backup/youtubedl-android/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 61, in run for e in atomoicparsleys: NameError: name 'atomoicparsleys' is not defined

```

**Comment by yausername** [comment]
Sorry, I made a typo. Have fixed it now.
I should be testing the chages before releasing :p

**Comment by xibr** [comment]
Yes, now it works.

I added the AtomicParsley library to my fork if someone wanted to use it or try it.

Thank you.
