### ISSUE TITLE
Hey Bro i need help 

### ISSUE THREAD

**Issue by shivam1608** [yausername/youtubedl-android#81]
Bro when i use ffmpeg to convert to audio it does not give the thumbnail on music 
So is there any way to set youtube thumbnails?

**Comment by muhammad-hamza-shahid** [comment]
Hey @shivam1608 I have read your problem I also faced the same problem and the reason is we are extracting audio from the video file and it only extract audio but not the metadata of that video file. A simple solution is that you have to extract the metadata from the same video to use the thumbnail, but remember it will provide the thumbnail of youtube which shows the downloads on it.

**Comment by xibr** [comment]
To embed thumbnails to audio or video need atomicparsley library.
